### ISSUE TITLE
Vert metrics have been modified

### ISSUE THREAD

**Issue by m4rc1e** [cadsondemak/charm-of-AU#10]
I previously set the metrics in ec2ce5953c43e3aee519e334bcae0ad916fe1f35. They have now been modified and made much looser.

![charm_spacing](https://user-images.githubusercontent.com/7525512/46772179-80f7d680-ccab-11e8-8873-b5c5f22fd9c8.gif)

cc @davelab6

**Comment by m4rc1e** [comment]
I'm in the process of making an update which scales the fonts.

Can I revert the family back to the previous set of vert metrics?

**Comment by parin-rungpattarathakun** [comment]
Yes of course.

**Comment by m4rc1e** [comment]
Thank you! I'll just bulldozer over it!
