### ISSUE TITLE
ขอคำปรึกษาเรื่องแบบของ Charm

### ISSUE THREAD

**Issue by parin-rungpattarathakun** [cadsondemak/charm-of-AU#2]
จากแบบเดิมที่มีการวาดตวัดยาวของ ไ โ ใ ทำให้ไม่ชัดเจนในบางกรณีเมื่อทับกับวรรณยุกต์ชั้น 2 จึงทดลอง แก้อยู่ 2 วิธีคือ 
1. ยังคงเก็บเจตนาเดิมแต่วาดใหม่ให้มีความชัดเจนมากขึ้น
2. คือลดความสูงของ ไ โ ใ ซึ่งก็จะเสียเจตนาเดิมไปบ้าง แต่คิดว่านะจะช่วยเรื่องลดระยะบรรทัด และเพิ่มความโปร่งระหว่างบรรทัดได้ เมื่อนำไปใช้งานจริง

ผมเลยอยากขอคำปรึกษาครับว่าควรเลือกแนวทางไหนดีครับ

![img_0467](https://user-images.githubusercontent.com/35288945/37347825-4d95b10a-2705-11e8-9a14-966b00553361.PNG)

แบบที่ 2 เมื่อเทียบกับแบบเดิมที่ leading เท่ากัน

![img_0468](https://user-images.githubusercontent.com/35288945/37347869-66aa04a2-2705-11e8-847d-629470fc2ae3.JPG)

**Comment by AnuthinWongsunkakon** [comment]
ในฟอนต์ตัวนี้การเลือกที่จะลดความสูงของไม้ต่างๆลงน่าจะทำให้ผิดเจตนาของแบบซึ่งอยากจะให้สะท้อง old style handwriting การทำให้ไม้ต่างๆต่ำลงมันเป็นวิธีของ type design สมัยใหม่ ยุคหลังๆที่ตอนนี้เริ่มถูกคอมเม้นท์ให้กลับไปสูงแล้ว แต่ก็ยังไม่สูงเท่าของเก่าโบราณ เพราะสูงไปก็ดูเก่าเกินอีก สมัยใหม่ก็สั้นเกินไปนิด คือมันติดกรณีแบบนั้นอยู่ในวิถีการออกแบบปัจจุบัน อย่างที่บอกว่าในเฟสนี้ เขาสะท้อนยุคสมัยแบบเก่า เราควรน่าจะตามแบบสมัยที่อบบนี้อยากให้เป็นนะครับ ไม่งั้นลดลงมามันจะดูใหม่ไป 

ปัญหาคือสูงแหละ แต่สูงเท่าไหร่ ก็อาจจะลดลงมาได้นิดหน่อยแต่ให้เจตนาที่เห็นคือมันยังสูงอยู่ เนื่องจากมันไม่มีกำหนดว่าต้องสูงเท่านั้นเท่านี้ แบบเป็นสเกลกำหนด ฉะนั้นทำอย่างไรก็ได้ให้ดูสูงกว่าที่คนทุกวันนี้จะเขียน   

อีกอย่างต้องเข้าใจว่า ไม้ต่างๆเคยเมื่อยุคนึงเป็น สระเอ แล้วต่อมาร์คข้างบนมาก่อน ฉะนั้นอย่างนั้ยมันควรที่จะสูงจากตัวสระเอขึ้นไปอย่างน้อยอีกเท่านึง หรือเกือบเท่านึงครับ

**Comment by parin-rungpattarathakun** [comment]
ขอบคุณครับ เป็นความรู้ใหม่เลยครับ @AnuthinWongsunkakon

**Comment by AnuthinWongsunkakon** [comment]
I just spotted out the word  โชว์ in your sample above. If you can tiptop the tail of ช a little bit so it won't touch with ์, it would be much better. @parin-rungpattarathakun Could you please make this adjustment?
