### ISSUE TITLE
การปรับความสูงของชุดตัวอักษรเพื่อเพิ่มพื้นที่ระหว่างบรรทัด

### ISSUE THREAD

**Issue by parin-rungpattarathakun** [cadsondemak/charm-of-AU#5]
จากแบบเดิมที่มีการไขว้กันไปมาระหว่างบรรทัดทำให้ช่องว่างระหว่างบรรทัดดูน้อยเกินไป เลยทดลองลดขนาดของตัวอักษรให้เล็กลงเพื่อเพิ่มช่องว่างระหว่างบรรทัด

ขนาดเดิม
![charm_old](https://user-images.githubusercontent.com/35288945/41403413-00ebd676-6fef-11e8-80fa-d7c48018f9b8.jpg)

ขนาดใหม่
![charm_new](https://user-images.githubusercontent.com/35288945/41403415-01dacef2-6fef-11e8-97bc-4a17730df20d.jpg)

**Comment by suppakit-** [comment]
สำหรับผมเห็นว่าขนาดที่ลดลงเพื่อเพิ่มพื้นที่ระหว่างบรรทัด อยู่ในระดับที่เหมาะสมแล้วครับ ยังไงรอความเห็นจากท่านอื่นๆ เพิ่มเติมครับ
