### ISSUE TITLE
ttx roundtrip fails

### ISSUE THREAD

**Issue by m4rc1e** [cadsondemak/charm-of-AU#7]
Just realised why #6 is producing FB errors.

It seems glyph **L_O_G_O_period_k_a_r_u_d_a** is the culprit.

As we can see, it is immensely complex. Please forgive my ignorance, what is the purpose of this glyph?

![screen shot 2018-08-20 at 14 18 17](https://user-images.githubusercontent.com/7525512/44342819-10d78c00-a484-11e8-8df5-84303ff87912.png)

**Comment by davelab6** [comment]
I suggest just removing it; this kind of thing is better off in a separate
logo font.

**Comment by suppakit-** [comment]
The Garuda often appear on Thai government document paper. The developer might think it’s a easy way for the user to just type it down. For me this is just ornament so removing it would be a good solution. I will remove it. Thank you for the report. :D

**Comment by m4rc1e** [comment]
Closing. Fixed in a13d80df8ca839f8a97a97f539c3cc0d1817b0c9
